In [1]:
import numpy as np


In [2]:
X = np.array([1.0, 0.5])
X

array([1. , 0.5])

In [3]:
w1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
w1.shape

(2, 3)

In [4]:
a1 = np.dot(X, w1)
a1.shape

(3,)

In [5]:
a1

array([0.2, 0.5, 0.8])

In [6]:
1.0*0.1 + 0.5*0.2

0.2

In [7]:
b1 = np.array([0.1, 0.2, 0.3])
a1 = np.dot(X, w1) + b1

In [8]:
a1

array([0.3, 0.7, 1.1])

In [9]:
x1 = np.array([[1, 2], [3, 4]])
x2 = np.array([[5, 6], [7, 8]])

In [10]:
print(x1)
print(x2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [11]:
x1.shape

(2, 2)

In [12]:
x2.shape

(2, 2)

In [13]:
np.dot(x1, x2)

array([[19, 22],
       [43, 50]])

In [14]:
x1 =np.array([[1, 2]])
x2 = np.array([[5, 6], [7, 8]])


In [ ]:
x1.shape