In [1]:
import numpy as np
a = np.array([0.3, 0.9, 5.0])
a

array([0.3, 0.9, 5. ])

In [2]:
a = np.array([0.3, -0.5, 5.0])
a

array([ 0.3, -0.5,  5. ])

In [3]:
def softmax(a):
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y

In [4]:
y = softmax(a)

In [6]:
y

array([0.00897694, 0.0040336 , 0.98698946])

In [7]:
np.sum(y)

1.0

In [8]:
a = np.array([1111, 2222, 3333])
y = softmax(a)


C:\Users\kyeongmin\anaconda3\envs\tensorflow-gpu\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  
C:\Users\kyeongmin\anaconda3\envs\tensorflow-gpu\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in true_divide
  after removing the cwd from sys.path.


In [9]:
y

array([nan, nan, nan])